### ISSUE TITLE
Issues with typography and line breaks in closers in recent volumes

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/frus#288]
As discussed with @machalou:

Last week @KerryHite raised a question about the TEI markup of document "closers," which contain signature blocks, in a recent volume delivered by our typesetter, Reagan vol. 5: missing bold and italics styling, missing line breaks between segments of signature blocks, and inconsistent use of some inline tags, like "affiliation". 

After analysis with @vak2ve, the solution involves a few parallel efforts:

1. The FRUS TEI Guidelines should be revised to clarify how closers should be encoded to ensure fidelity to the printed edition and eliminate ambiguity of semantic tags like "affiliation" (which was introduced by our typesetter in 2014 and only has 800-odd uses, in comparison to the 200,000+ closers in the full corpus). In the volume in question, the issue affects almost every closer, not just those with the "affiliation" tag. Virginia will draft a set of changes to the Guidelines, using the FRUS XPath Explorer tool to assess recent and corpus-wide practices, and @machalou and I will have the chance to review the proposed revisions and ask questions before we accept them. 
2. Our FRUS TEI schemas should also be updated to give us and our typesetter helpful contextual warnings and errors surrounding closers. While drafting the Guidelines updates, Virginia will also identify opportunities to add Schematron checks. Once we have adopted the revisions to the Guidelines and schemas, we will supply the updated Guidelines to the typesetter. 
3. The volume where the issues were identified will need to be reviewed for conformance to the updated Guidelines. PR #287 addressed some of these issues (focusing on "affiliation" styling and line breaks around it), so I will accept this and merge it into the FRUS repository. Building on that, I've asked Virginia to apply the necessary changes to bring the volume into conformance with all aspects of the updated Guidelines and assess what would be needed to identify cases in other recent volumes with this issue. We should either be able to script the fixes or, at worst, use the FRUS XPath Explorer to review instances of closers and quickly apply manual fixes.
4. I'd like to share the FRUS XPath Explorer with folks in E&P to demonstrate how it can help us spot patterns in FRUS digital *and* print editions and drill into volumes to apply fixes where needed. I think it could be useful to folks for use in their editing work.

Looking ahead, I've asked Virginia to resurrect a project she had been working on in late 2019 just before she switched her focus to the indexing project: the preparation of a "FRUS Visual Style Guide" - a survey of FRUS print and digital edition style practices, with ample illustrations of printed pages, TEI, and rendered HTML. She'd already drafted several sections, including openers, closers, and lists. Kerry's question about closers clearly reminded us of this project, and now that Virginia is wrapping up edits on her 2nd index, this is an opportune time to pick the Visual Style Guide project back up. It'll help us, our vendors, and our developers understand how FRUS should be styled and encoded.

**Comment by joewiz** [comment]
**Update:**

- [x] Step 1: Closed by #289.
- [x] Step 2: Started by #289 and continued in the master branch, including our first ever use of XSpec as a test suite for our Schematron. 
- [ ] Step 3: Closed for Reagan by #297 and Carter by #296. @vak2ve will assess and tackle earlier subseries as time allows. Updated schemas to be supplied to typesetter.
